version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: nestjs-api-key-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Disable authentication for development
      MONGO_INITDB_DATABASE: nestjs-api-key-db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - api-key-network

  # Optional: Mongo Express for database management via web UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: nestjs-api-key-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb
    networks:
      - api-key-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  api-key-network:
    driver: bridge
